### ISSUE TITLE
Parsing silently fails for mutations

### ISSUE THREAD

**Issue by mylesmegyesi** [excitement-engineer/graphql-iso-date#72] opened 2017-12-28 14:55 UTC
Consider this example:

```graphql
# Schema
type LogInput {
  message: String!
  createdAt: Date!
}

type Log {
  id: ID!
  message: String!
  createdAt: Date!
}

type Mutation {
  createLog(log: LogInput!): Log!
}

# query
mutation {
  createLog({
    message: "Hello, World!",
    createdAt: "2017-01-001" # invalid
  }) {
    message,
    createdAt
  }
}
```
In this example, parsing silently fails and sets the `createdAt` to `null`. I think it would be more useful to thrown an error in this case.

**Comment by Nume** [comment] 2018-01-07 16:43
I have a similar problem. And the issue seems to be that validation is handled differently in `parseValue` and `parseLiteral`. If validation fails in `parseValue`(e.g using variables in your query) it throws and exception and if validation fails in `parseLiteral`(e.g using inline values in your query) null is returned. 
Is this the expected behavior? @excitement-engineer

**Comment by excitement-engineer** [comment] 2018-01-08 19:40
It seems like this is a bug. If an invalid value is provided then it should throw an error. Would you care to provide a test case to the code that reproduces this error and that fixes it? I will then be able to take it into account in the next release

**Comment by marcusstenbeck** [comment] 2018-01-13 23:26
I encountered the same error, for the time being downgrading to `graphql@0.11.x` works, but I also submitted a PR that fixes the issue, and cleans up the code a bit. :)

**Comment by excitement-engineer** [comment] 2018-02-03 16:57
Thanks for reporting this, it is fixed in #76.

**Closed by excitement-engineer** 2018-02-03 16:57 UTC

**Comment by excitement-engineer** [comment] 2018-02-03 19:27
I have release version 3.4.0 which includes the fix.

**Comment by jhnferraris** [comment] 2018-04-11 13:53
Can anyone confirm if the parsing silently fails on GraphQLDateTime on version `^3.5.0`? I have this `schema` snippet

```
input payload{
    durationStart: GraphQLDateTime!
    durationEnd: GraphQLDateTime!
  }

mutation {
  sendSchedule(payload: {
    durationStart:"04-04 14:59:59xxxxx" # invalid
    durationEnd: "2018-04-04T15:00:00"
  }) {
     durationStart
     durationEnd
  }
}
```

In the resolver `args.payload` log is showing:

```
durationStart: '04-04 14:59:59xxxxx',
durationEnd: '2018-04-04T15:00:00
```

therefore it is "passing"?

Thanks for the assist!
